### ISSUE TITLE
installation and import issue

### ISSUE THREAD

**Issue by GhsJahanmir** [raghavagps/Pfeature#7]
Hi,

I faced two different errors when trying to import pfeature in both anaconda prompt and jupyter notebook on Windows.

1-Error on jupyter

ModuleNotFoundError: No module named 'Pfeature'

2- Error in anaconda prompt:

>>> from Pfeature.pfeature import aac_wp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\myusername\Anaconda3\lib\site-packages\Pfeature\pfeature.py", line 31, in <module>
    PCP= pd.read_csv(paths_2+'./PhysicoChemical.csv', header=None)
  File "C:\Users\myusername\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\myusername\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\myusername\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "C:\Users\myusername\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "C:\Users\myusername\Anaconda3\lib\site-packages\pandas\io\common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/PhysicoChemical.csv'

has anyone faced the same issue or any suggestions?
Thanks in advance,

**Comment by agboken** [comment]
the same thing I have been facing for hours now. Please, have you been able to come up with any solution?

**Comment by AledHe** [comment]
Hello, please check pfeature.py in the lib.

The author may use Mac or Linux-based OS to develop this library, so here are some problems with the original path code:
```
paths = [find('aa_attr_group.csv','/')]
paths_1 = paths[0].split('/')[:-1]
paths_2 = '/'.join(paths_1)
```

to resolve this issue,

replace these three line with:
```
current_directory = os.path.dirname(os.path.abspath(__file__))

path_to_aa_attr_group = find('aa_attr_group.csv', current_directory)

if path_to_aa_attr_group:
    paths_1 = os.path.split(path_to_aa_attr_group)[:-1]
    paths_2 = os.path.join(*paths_1)
else:
    print("File 'aa_attr_group.csv' not found")
    paths_2 = current_directory
```
